### ISSUE TITLE
Bad appearance in Obsidian 0.16+

### ISSUE THREAD

**Issue by JeppeKlitgaard** [claremacrae/reveal-active-file-button-plugin#2]
I have noticed after switching to Obsidian 0.16+ that the icon for Reveal Active File is not formatted properly:
![image](https://user-images.githubusercontent.com/1814611/194287739-19e475bd-f705-445c-b4b5-caaa83cd7cf4.png)

This is due to it missing the `clickable-icon` class.

I was about to submit a PR when I noticed @OfficerHalf has already done this in #1. Any chance you could merge this @claremacrae and push a new release?

Thanks for the lovely plugin, I should add.

**Comment by claremacrae** [comment]
Thank you both for the prompt.
Just released in [2.0.2](https://github.com/claremacrae/reveal-active-file-button-plugin/releases/tag/2.0.2) and available in Obsidian.
