### ISSUE TITLE
Open folder tree when showing highlighted file

### ISSUE THREAD

**Issue by danraymond** [claremacrae/reveal-active-file-button-plugin#4]
If my folder tree is not open on the branch where my fiIe is can't see where the file is, as only the actual file gets highlighted.

**Comment by claremacrae** [comment]
This has been fixed and I need to do a release. 

I will hold off until there is any info in #5 to allow me to investigate that, so I can figure out if it is actionable.

**Comment by claremacrae** [comment]
The work around is to click the button a second time.

**Comment by claremacrae** [comment]
@danraymond I've just released 2.0.3 so this should be fixed.
