### ISSUE TITLE
icon missing since update

### ISSUE THREAD

**Issue by danraymond** [claremacrae/reveal-active-file-button-plugin#5]
Since the latest obsidian update I can't see the icon in the folder tree icon bar. I have tried reinstalling the plugin but to no success

**Comment by claremacrae** [comment]
It works for me, so there currently isn’t a lot I can do. 

Feel free to supply info. 

What version of this plugin and Obsidian?
What platform?
Send a screenshot. 
Does it work when all other plugins are turned off and default theme, no snippets?

**Comment by claremacrae** [comment]
Hi @danraymond, Feel free to try out the latest release.

I'm going to close this for now as there isn't any info to do anything about it.

If the problem still occurs and you can provide the info requested above, I may be able to investigate.
